version: '3.8'

services:
  web:
    build: .
    container_name: secret-santa
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - data:/app/instance
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:///santaDB.db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 60s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  data: