version: '3.8'

services:
  web:
    build: .
    container_name: secret-santa
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - data:/app/instance
    environment:
      - FLASK_APP=main.py
      - FLASK_ENV=production
      - SQLALCHEMY_DATABASE_URI=sqlite:///santaDB.db
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M

volumes:
  data: